### ISSUE TITLE
Missing web.zip in step 5

### ISSUE THREAD

**Issue by joapim** [aws-samples/aws-step-functions-notification-workflow#1]
I get a "page not found" error when I try to download the file. Appreciate if you can reupload the file

**Comment by nerdyness** [comment]
Hi @joapim, you can find the content of the [web.zip here](https://github.com/aws-samples/aws-step-functions-notification-workflow/tree/master/src/web).

@gurubayari could you please update the documentation? I tried but couldn't push my feature branch due to a permissions error

**Comment by gurubayari** [comment]
Modified the documentation to include the link for web folder content.
